### ISSUE TITLE
how to generate the free mask with my own  custom data?

### ISSUE THREAD

**Issue by Vincent630** [NVlabs/FreeSOLO#5]
i have a instance segmentation dataset ,but its label mask is too accurate compare free mask,i just want to konw how you generate free mask?and i i use my pretrained model(solo model) to generate the free mask ,is that a bad idea?please let me konw if that's not so unconvient ,thaks a lot......

**Comment by Vincent630** [comment]
sorry ,i did not notice that part at fist .

**Comment by EavnJeong** [comment]
Can you tell me how?
